name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install --force
      - run: npm run build
      - name: Upload build to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: build
      - name: Cloudflare deploy
        run: curl -X POST ${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}